# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  routing_loader:
    include_format: false
    default_format: json
  #
  format_listener:
    rules:
      - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
  #
  body_converter:
    enabled: true
  #
  serializer:
    serialize_null: true
  #
  view:
    formats: { json: true, xml: false, rss: false }
    view_response_listener:  true
