security:
    #
    encoders:
        App\Entity\User\User:
            algorithm: bcrypt
            cost: 12
    #
    providers:
        user_db:
            entity:
                class: App\Entity\User\User
                property: username
    #
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # JSON Authentication Endpoint
        apilogin:
            pattern:  ^/apilogin
            stateless: true
            anonymous: true
            json_login:
                check_path: /apilogin
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        api:
            pattern: ^/api/
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
            stateless: true
            anonymous: ~
        default:
            pattern: ^/
            provider: user_db
            guard:
                authenticators:
                    - App\Security\FormLoginAuthenticator
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login
                # field names for the username and password fields
                username_parameter: _username
                password_parameter: _password
                # csrf token options
                csrf_parameter:       _crsf_token
                csrf_token_id:        authenticate
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /logout
                target: /login
                invalidate_session: false
            logout_on_user_change: true
    #
    access_control:
        - { path: ^/apilogin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/apidoc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
    #
    role_hierarchy:
        ROLE_API_USER: [ROLE_USER]
